DROP DATABASE IF EXISTS huddle_dev;
CREATE DATABASE huddle_dev;

\c keepsake_dev;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
)

DROP TABLE IF EXISTS teams;

CREATE TABLE teams(
    id SERIAL PRIMARY KEY,
    owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE
    name VARCHAR(255) NOT NULL,
    desc TEXT,
    created_at TIMESTAMPTZ NOT NULL
)